editApplication:

 editApplicationByIdSearch: >
  select document_details.application_id as applicationId,document_details.sender_name as senderName,
  document_details.sender_poc as senderPointOfContact,document_details.sender_contact as senderContact,
  document_details.date_received as dateReceived,doc_status.status as status,
  document_details.priority as priority,document_details.reference_number as referenceNumber,document_details.subject as subject,document_details.document_type as documentType ,
  document_details.document_remarks as additionalComment from document_details INNER JOIN doc_status ON document_details.id = doc_status.doc_id
  where document_details.application_id= :applicationId;
  
 updateDocumentDetailsTable: >
  UPDATE scgj_pmts.document_details 
  SET sender_name= :senderName,sender_poc =:senderPoc,
  sender_contact=:senderContact,date_received=:dateReceived,priority= :priority,reference_number=:referenceNumber,subject=:subject,document_path= :documentPath,document_remarks= :documentRemarks
  WHERE document_details.application_id= :applicationId;
  
 updateDocumentOwner: >
  UPDATE scgj_pmts.doc_status SET owner_id= :ownerId Where doc_id= :documentId;
 
 idByApplicationId: >
  SELECT id FROM scgj_pmts.document_details where application_id= :applicationId;
 
 applicationIdWithStatusNotStarted: >
  select document_details.application_id from document_details INNER JOIN doc_status ON  document_details.id = doc_status.doc_id;

 updateDocumentDetailsTableWithoutFile: >
  UPDATE scgj_pmts.document_details 
  SET sender_name= :senderName,sender_poc =:senderPoc,
  sender_contact=:senderContact,date_received=:dateReceived,priority= :priority,reference_number=:referenceNumber,subject=:subject,document_remarks= :documentRemarks
  WHERE document_details.application_id= :applicationId;
  
 updateAuditTableDetails: >
  INSERT INTO scgj_pmts.audit_table (application_id, sender_name, subject, assigned_to,  document_path, document_type, date_status_update, status, assigned_by) VALUES
  (:applicationId, :senderName, :subject, :ownerId, :documentPath,:documentType,curdate(), :status, :email);
   