registerApplication:

 departmentHeadNamesSql: >
  select name from users where role_type='DH';
 totalNumberOfApplications: >
  Select count(id) from scgj_pmts.document_details where document_type=:document_type;
 submitPostDetails: >
  INSERT INTO document_details(application_id,sender_name,sender_poc,sender_contact,date_received,date_of_entry,priority,subject,document_type,reference_number,document_path,document_remarks) VALUES
  (:applicationId,:senderName,:senderPoc,:senderContact,:dateReceived,curdate(),:priority,:subject,:documentType,:referenceNumber,:documentPath,:documentRemarks);
 documentOwnerId: >
  select id from users where name= :ownerName and role_type='DH';
 submitDocumentStatus: >
  INSERT INTO scgj_pmts.doc_status (owner_id, status, doc_id) VALUES (:ownerId,:status,:documentId);
 applicationIdById: >
  SELECT application_id FROM scgj_pmts.document_details where id = :docId;
 insertAuditTableWhileRegister: >
  INSERT INTO scgj_pmts.audit_table (application_id, sender_name, subject, priority, assigned_to,  document_path, document_type, reference_number,date_status_update, status, assigned_by) VALUES
  (:applicationId, :senderName, :subject, :priority, :ownerId, :documentPath,:documentType,:referenceNumber,curdate(), "Not Started", :email);
